### ISSUE TITLE
It only downloads the first attachment of each email.

### ISSUE THREAD

**Issue by fireattack** [munir131/attachment-downloader#11]
I tried both "from:" and label approach, the result is same.

If the email has multiple attachments (in my case, they are all images), only the first one will be downloaded.

Also, when I'm using the "from:" filter, it's even worse: I found at least one email wasn't downloaded at all (it's exactly the 51th one out of 51 emails that isn't downloaded, not sure if relevant.)

**Comment by munir131** [comment]
@fireattack I will check that.
