### ISSUE TITLE
Hitting rate limits

### ISSUE THREAD

**Issue by gopi-ar** [munir131/attachment-downloader#13]
I get this error with any search with more than a few emails:

    GaxiosError: Too many concurrent requests for user
    at Gaxios.<anonymous> (/attachment-downloader/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/attachment-downloader/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {

It'll be great if this library could throttle itself to stay within Gmail's API limits!

**Comment by blueteq** [comment]
Is there a way around this?  I was about to do a nice bulk starred download and this happened?

**Comment by munir131** [comment]
@blueteq Rate limit is not implemented yet in this tool.

**Comment by blueteq** [comment]
> @blueteq Rate limit is not implemented yet in this tool.

Thank you for the quick reply, is the limit per day or per request? Then I can plan the pulls?

**Comment by munir131** [comment]
> > @blueteq Rate limit is not implemented yet in this tool.
> 
> Thank you for the quick reply, is the limit per day or per request? Then I can plan the pulls?

It is 250 request per user per second. https://developers.google.com/gmail/api/v1/reference/quota

**Comment by munir131** [comment]
@gopi-ar & @blueteq I hope above commit will solve your rate limit issue

**Comment by gopi-ar** [comment]
Thank you for pushing a fix! While this solves the rate limit, it doesn't download more than 100 attachments in one go. Maybe something to do with ` if (counter === 100)`?

**Comment by munir131** [comment]
It can download more than 100 attachment. 100 number is just for number of attachment in one batch. I will confirm yet
